version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
      - store_artifacts:
          path: build/konan/bin
          destination: bin